# use /schedule YYYY-MM-DD <military time> in your PR to set a merge time
name: Merge Scheduled PRs

on:
    pull_request:
        types: [opened, edited]
    issue_comment:
        types: [created]
    schedule:
        - cron: "0 * * * *"

permissions:
    contents: write
    pull-requests: write
    repository-projects: write
jobs:
    merge_schedule:
        runs-on: ubuntu-latest
        steps:
            - uses: gr2m/merge-schedule-action@v1.x
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
